[package]
name = "guest-types"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
eth-rlp-types = { workspace = true }

serde = { version = "1.0", features = ["derive"] }
risc0-zkvm = { version = "1.2.1", default-features = false, features = ['std'] }
